# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8372e83e4bdf94366f97bcdafb92747374f19ef9d7460e060c496c72c2260973a19e4ee76643ade0742b5df866553358fcbcf69534794933c3e6866c23afd60e

test:
  secret_key_base: 1fbc721dadb0c37b9cddc7a1a5b49a88e8b9751294e012a942be12ba4f0099cc0017c35fb05aef74b662699b55390617390c0da6c432dc372b20ee7076e028d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
